### PR TITLE
[WIP] Adds support for detecting overwritten custom frontend files on top o…

### PR DESCRIPTION
**Pull request by hostep**
…f Hyvä themes.

This is a very hacky way of adding support for [Hyvä themes](https://hyva.io/) as a base theme.

Currently this tool does not support detecting changes in custom themes build on top of Hyvä themes.
For example, I was trying to upgrade Hyvä from one version to another and was hoping that this tool would help me figure out which overwritten files in our custom theme needed to be looked at. But currently the tool doesn't support this.

The PR is in WIP status, because I'm like 99% sure this isn't the correct way of adding support for this.

In fact, I believe there might be a bug in the tool which does currently not support base themes at all.
Magento adds almost all their frontend files (xml, phtml, html, js) through modules and not through their blank or luma themes.

There are currently only a few limited files that are interesting to this tool in their base themes and I think the tool currently is not able to analyse change in those files (not tested though), some numbers to demonstrate how few files are in those themes (the majority of files in those themes are `less` files):
- 0 phtml files in Magento/blank
- 0 html files in Magento/blank
- 3 js files in Magento/blank
- 5 xml files in Magento/blank
- 2 phtml files in Magento/luma
- 18 html files in Magento/luma
- 0 js files in Magento/luma
- 9 xml files in Magento/luma 

This is probably also why Hyvä themes aren't working out of the box since the 2 Hyvä themes (reset & default) do put all their frontend files inside the theme.

I'm not sure what the best way would be to support this in a more generic way that can work with all themes and random file structures, and have not a lot of time to investigate this properly unfortunately.

### Checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] Tests have been ran / updated

### CODE REVIEW

**Comment by convenient** [comment]
Hello

I am reading the above to try and understand and make sure I follow it properly, as I've not had any experience with Hyva yet but I wanted to dive right in on
>In fact, I believe there might be a bug in the tool which does currently not support base themes at all.
>Magento adds almost all their frontend files (xml, phtml, html, js) through modules and not through their blank or luma themes.

Can you clarify exactly how this use case isn't covered?

For our older non PWA projects we had a base-theme we install via composer, then customise further in the theme within the project, this resulted in changes like the following being reported on the upgrade from 2.3 to 2.4.
```
| Override (phtml/js/html) | vendor/magento/module-checkout/view/frontend/templates/cart/shipping.phtml                            | vendor/ampersand/magento2-base-theme/Magento_Checkout/templates/cart/shipping.phtml                             |
| Override (phtml/js/html) | vendor/magento/module-checkout/view/frontend/templates/cart/shipping.phtml                            | app/design/frontend/RedactedProject/default/Magento_Checkout/templates/cart/shipping.phtml                          |
```

In reality this translates to 
- `app/design/frontend/RedactedProject/default/Magento_Checkout/templates/cart/shipping.phtml` overrides
- `vendor/ampersand/magento2-base-theme/Magento_Checkout/templates/cart/shipping.phtml` overrides
- `vendor/magento/module-checkout/view/frontend/templates/cart/shipping.phtml`

You can see the same template is reported twice as its overridden in two active themes which leaves it up to the user of this tool to patch appropriately. (A bit annoying its reported twice and isnt smart enough to work out the "true" template but thats a different thing.)

I also currently have a test setup covering a theme overriding a `.phtml` from a module, like so.
```
| Override (phtml/js/html) | vendor/ampersand/upgrade-patch-helper-test-module/src/module/view/frontend/templates/checkout/something.phtml | app/design/frontend/Ampersand/theme/Ampersand_TestVendor/templates/checkout/something.phtml            |
```

This translates to 
- `app/design/frontend/Ampersand/theme/Ampersand_TestVendor/templates/checkout/something.phtml` overides
- `vendor/ampersand/upgrade-patch-helper-test-module/src/module/view/frontend/templates/checkout/something.phtml`

Can you clarify what isn't working? Is it like the following kind of chain you are talking about?
- `app/code/Namespace/Module/path/to/something.phtml` overrides
- `vendor/namespace/theme/path/to/something.phtml` overrides
- `vendor/magento/theme-frontend-luma/path/to/something.phtml `

Thanks :)

**Comment by convenient** [comment]
If it helps clarify, currently the tests run with the themes setup like

https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/blob/630e85b388ebbc647af655070c364aadc22562da/dev/TestModule/app/design/frontend/Ampersand/theme/theme.xml#L3-L4

https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/blob/630e85b388ebbc647af655070c364aadc22562da/dev/TestVendorModule/src/theme/theme.xml#L3-L4

**Comment by hostep** [comment]
I may have made some assumptions that aren't correct. When I find some more time, I'll try to research and put some more info here, but that could take a while.

Some quick example of a specific Hyvä file we have overwritten that didn't get reported before the changes of this PR (well none of of the overwritten Hyvä files got reported):

- `app/design/frontend/Vendor/some-theme/Magento_Customer/templates/form/register.phtml`
- `vendor/hyva-themes/magento2-default-theme/Magento_Customer/templates/form/register.phtml`

Be aware that the `Hyva/default` theme has the `Hyva/reset` theme as parent which in itself does not have a parent, so Magento's blank or luma themes are not involved in this chain.

**Comment by convenient** [comment]
Hmmm that sounds like the case I had covered with

- `app/design/frontend/Ampersand/theme/Ampersand_TestVendor/templates/checkout/something.phtml`
- `vendor/ampersand/upgrade-patch-helper-test-module/src/module/view/frontend/templates/checkout/something.phtml` 

The only difference being that my example theme falls back to Luma. 

I'm not sure that we do anything special that requires all themes to fallback to a Magento core theme, so I would have expected that your Hyva themes would have been detected by this piece of code

https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/blob/630e85b388ebbc647af655070c364aadc22562da/src/Ampersand/PatchHelper/Helper/Magento2Instance.php#L60-L70

I do not have access to Hyva so cannot debug properly this myself I am afraid, but you know where to get me on slack and available here. Maybe this is something to do with having two themes defined in `vendor` that fall back to eachother, but I'm not sure if that makes sense, just an idea.

**Comment by convenient** [comment]
@hostep I've got access to Hyva now.

Can you share
- What initial hyva version you were on
- What version you upgraded to 
- List of all installed hyva deps (just in case 🤷‍♂️)

**Comment by hostep** [comment]
Hi @convenient

Thanks for taking the time for this and great to hear you have access to Hyvä themes now 🙂 !

So:
- We are trying to upgrade `hyva-themes/magento2-default-theme` from 1.1.3 to 1.1.6 (and some other hyvä modules)
- Just in case (but I don't think this is very relevant), before the upgrade we had these versions installed:
```
- hyva-themes/magento2-default-theme      1.1.3
- hyva-themes/magento2-email-module       1.0.2
- hyva-themes/magento2-graphql-tokens     1.0.3
- hyva-themes/magento2-hyva-checkout      dev-main ed3b322
- hyva-themes/magento2-luma-checkout      1.0.3
- hyva-themes/magento2-reset-theme        1.1.0
- hyva-themes/magento2-smile-elasticsuite dev-master
- hyva-themes/magento2-theme-fallback     1.0.0
- hyva-themes/magento2-theme-module       1.1.3
```

Afterwards we had these ones:
```
- hyva-themes/magento2-default-theme      1.1.6
- hyva-themes/magento2-email-module       1.0.3
- hyva-themes/magento2-graphql-tokens     1.0.3
- hyva-themes/magento2-graphql-view-model 1.0.1
- hyva-themes/magento2-hyva-checkout      dev-main ed3b322
- hyva-themes/magento2-luma-checkout      1.1.1
- hyva-themes/magento2-reset-theme        1.1.0
- hyva-themes/magento2-smile-elasticsuite dev-master
- hyva-themes/magento2-theme-fallback     1.0.1
- hyva-themes/magento2-theme-module       1.1.6
```

Without the changes from this PR, nothing was reported from our overwrites.
With the changes from this PR 40 overwrites were found, including the one I mentioned before.

**Comment by hostep** [comment]
Let me close this PR, the last couple of times I've used this tool on a Hyvä based install, it correctly detected changes.

No idea what I did wrong the first time I tested this ... 🙂

**Comment by convenient** [comment]
Thanks @hostep 👍

**Comment by convenient** [comment]
@hostep you were right on the money with this code change, I just didnt think about it properly at the time I think.

Addressed in https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/pull/80

**Pull request closed without merging**
