### PR TITLE
Added extra column when using the --auto-theme-update flag to indicate if the patch got applied or not

### PR DESCRIPTION
**Pull request by hostep**
### Checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [?] Tests have been ran / updated

### Description

Adds an extra column, to indicate if a patch was auto applied when using the `--autho-theme-update` flag.
So it becomes easier to figure out which files you need to manually check afterwards and which ones not.
Example:

```
+-------+--------------------------+------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+--------------+
| Level | Type                     | File                                                                                                                         | To Check                                                                                                                 | Auto applied |
+-------+--------------------------+------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+--------------+
| WARN  | Override (phtml/js/html) | vendor/hyva-themes/magento2-default-theme/Hyva_Theme/templates/ui/loading.phtml                                              | app/design/frontend/Vendor/hyva-theme/Hyva_Theme/templates/ui/loading.phtml                                              | No           |
| WARN  | Override (phtml/js/html) | vendor/hyva-themes/magento2-default-theme/Magento_Bundle/templates/catalog/product/view/price.phtml                          | app/design/frontend/Vendor/hyva-theme/Magento_Bundle/templates/catalog/product/view/price.phtml                          | Yes          |
| WARN  | Override (phtml/js/html) | vendor/hyva-themes/magento2-default-theme/Magento_Bundle/templates/catalog/product/view/summary.phtml                        | app/design/frontend/Vendor/hyva-theme/Magento_Bundle/templates/catalog/product/view/summary.phtml                        | Yes          |
| WARN  | Override (phtml/js/html) | vendor/hyva-themes/magento2-reset-theme/Magento_ReCaptchaCustomer/layout/override/base/customer_account_edit.xml             | app/design/frontend/Vendor/hyva-theme/Magento_ReCaptchaCustomer/layout/customer_account_edit.xml                         | No           |
| WARN  | Override (phtml/js/html) | vendor/hyva-themes/magento2-smile-elasticsuite/src/view/frontend/templates/catalog/layer/filter/js/attribute-filter-js.phtml | app/design/frontend/Vendor/hyva-theme/Hyva_SmileElasticsuite/templates/catalog/layer/filter/js/attribute-filter-js.phtml | Yes          |
| WARN  | Override (phtml/js/html) | vendor/hyva-themes/magento2-smile-elasticsuite/src/view/frontend/templates/catalog/layer/filter/js/slider-filter-js.phtml    | app/design/frontend/Vendor/hyva-theme/Hyva_SmileElasticsuite/templates/catalog/layer/filter/js/slider-filter-js.phtml    | Yes          |
| WARN  | Override (phtml/js/html) | vendor/hyva-themes/magento2-theme-module/src/view/frontend/templates/page/js/private-content.phtml                           | app/design/frontend/Vendor/hyva-theme/Hyva_Theme/templates/page/js/private-content.phtml                                 | Yes          |
| WARN  | Preference               | vendor/hyva-themes/magento2-theme-module/src/ViewModel/Cart/GraphQlQueriesWithVariables.php                                  | Vendor\ExtendedHyvaTheme\ViewModel\Cart\GraphQlQueriesWithVariables                                                      | N/A          |
| WARN  | Preference               | vendor/hyva-themes/magento2-theme-module/src/ViewModel/ProductPrice.php                                                      | Vendor\ExtendedHyvaTheme\ViewModel\ProductPrice                                                                          | N/A          |
+-------+--------------------------+------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+--------------+
```

### Questions

- Is the column header 'Auto applied' good, or clear enough? Would like to make it shorter but having a hard time finding a better name
- The updated functional test won't be enough, this was added after messing around for 2-3 hours with trying to get my local setup to get it up and running, but it ran so slowly (probably my own fault, because lack of Docker knowledge) that I gave up and only added a little test (which may or may not work).
- I've noticed that the auto apply patch tries to update `.xml` files, which tends to not be necessary, as xml files are merged with their parent(s), so I don't know if we should already try to prevent this from happening automatically, or if we need to leave this up to the user to double check?

### CODE REVIEW

**Comment by convenient** [comment]
@samicoman @hostep I cannot push to this fork because of https://github.com/orgs/community/discussions/5634

### Answering your questions

> Is the column header 'Auto applied' good, or clear enough? Would like to make it shorter but having a hard time finding a better name

As this column only appears when you pass in the `--autho-theme-update` flag I expect that it's sufficient. Naming things has never been my strong suit either (as evidenced by the mouthful that is `ampersand-magento2-upgrade-patch-helper` 🙃 ) 

>The updated functional test won't be enough, this was added after messing around for 2-3 hours with trying to get my local setup to get it up and running, but it ran so slowly (probably my own fault, because lack of Docker knowledge) that I gave up and only added a little test (which may or may not work).

Hopefully fixed by https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/pull/93

>I've noticed that the auto apply patch tries to update .xml files, which tends to not be necessary, as xml files are merged with their parent(s)

That's a good point, but so far this tool has been applying the patch in this case so I wonder if its "expected behaviour" at this point. There have been no errors reported because of it, and the new column will only make it clearer that this has occurred.

### Next steps - Patch to apply

Please sync up with the master branch, then apply the following patch to get a green build.

```diff
diff --git a/dev/phpunit/functional/FunctionalTests.php b/dev/phpunit/functional/FunctionalTests.php
index 4ed4f6d..eaaf55f 100644
--- a/dev/phpunit/functional/FunctionalTests.php
+++ b/dev/phpunit/functional/FunctionalTests.php
@@ -140,8 +140,10 @@ class FunctionalTests extends \PHPUnit\Framework\TestCase
             "This file did not get auto patched properly"
         );
 
-        $output = implode(PHP_EOL, $output);
+        $lastLine = array_pop($output);
+        $this->assertStringStartsWith('You should review the above', $lastLine);
 
+        $output = implode(PHP_EOL, $output);
         $this->assertEquals($this->fileGetContents('/dev/phpunit/functional/expected_output/magentom23-auto-apply.out.txt'), $output);
     }
 
diff --git a/dev/phpunit/functional/expected_output/magentom23-auto-apply.out.txt b/dev/phpunit/functional/expected_output/magentom23-auto-apply.out.txt
index 659c48b..ef008d3 100644
--- a/dev/phpunit/functional/expected_output/magentom23-auto-apply.out.txt
+++ b/dev/phpunit/functional/expected_output/magentom23-auto-apply.out.txt
@@ -3,3 +3,6 @@
 +-------+--------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------------+--------------+
 | WARN  | Override (phtml/js/html) | vendor/magento/module-bundle/view/frontend/templates/js/components.phtml | app/design/frontend/Ampersand/theme/Magento_Bundle/templates/js/components.phtml | Yes          |
 +-------+--------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------------+--------------+
+WARN count: 1
+INFO count: 0
+For docs on each check see https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/blob/master/docs/CHECKS_AVAILABLE.md
```

**Comment by convenient** [comment]
> In the next runs, the auto applied patch is still active and the test fails again when trying to apply it again.
So we need to somehow revert back to the state before the auto applied patch got executed. How would you suggest to handle this?

@hostep I'm wondering how this would actually be used in the real world. Do you ever run this tool twice with the auto patch? Would it be better to come up with a mechanism so that it reports `Auto Patched=Yes` even if you re-run it N times? 🤔  Maybe could record something in `/tmp/m2upgradehelper/project-path-sanitised-patchfilehash` to say whether it has been successfully applied during an execution, so that repeat runs can report `Auto Patched=Yes` ? I don't really know though, I don't use this flag.

>It would also be great if we can add some more patches to test the auto apply, because now we only test for one that's successful, would be great if we can test as well for one that fails and for one that's irrelevant (Plugin, Preference, ...).
However, it'll take me too long to get this figured out at the moment. So I'll leave it at the current state for now. Maybe when I find more time in the future, I can take another stab.

Agreed more test coverage would be nice, but this introduces little risk so once we work out the above point I'll be content enough to merge.

>Also, the performance improvements done in https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/pull/93 are really great, it now only takes ~2 minutes to execute the tests from the m23 environment on my local machine. Thanks!

Really good to hear 🙌

**Comment by hostep** [comment]
> @hostep I'm wondering how this would actually be used in the real world. Do you ever run this tool twice with the auto patch? Would it be better to come up with a mechanism so that it reports Auto Patched=Yes even if you re-run it N times? 🤔 Maybe could record something in /tmp/m2upgradehelper/project-path-sanitised-patchfilehash to say whether it has been successfully applied during an execution, so that repeat runs can report Auto Patched=Yes ? I don't really know though, I don't use this flag.

Ah sorry, you mistunderstood.

This only happens when executing the **tests** twice after each other locally, hasn't got anything to do with using the tool itself.
This is not a problem with the github actions here, but only locally when trying to run the tests without having to destroy and setting up the environment again each single time.

> Agreed more test coverage would be nice, but this introduces little risk so once we work out the above point I'll be content enough to merge.

Okay, good for me 👍 🙂

**Comment by convenient** [comment]
@hostep would something like this work?

```diff
diff --git a/dev/phpunit/functional/FunctionalTests.php b/dev/phpunit/functional/FunctionalTests.php
index 446b354..bffcec6 100644
--- a/dev/phpunit/functional/FunctionalTests.php
+++ b/dev/phpunit/functional/FunctionalTests.php
@@ -116,6 +116,12 @@ class FunctionalTests extends \PHPUnit\Framework\TestCase
             BASE_DIR . '/dev/instances/magentom23/vendor.patch',
             BASE_DIR . '/dev/instances/magentom23/vendor.patch.bak'
         );
+        if (!is_file(BASE_DIR . '/dev/instances/magentom23/vendor/magento/module-bundle/view/frontend/templates/js/components.phtml.orig')) {
+            copy(
+                BASE_DIR . '/dev/instances/magentom23/vendor/magento/module-bundle/view/frontend/templates/js/components.phtml',
+                BASE_DIR . '/dev/instances/magentom23/vendor/magento/module-bundle/view/frontend/templates/js/components.phtml.orig'
+            );
+        }
         copy(
             BASE_DIR . '/dev/phpunit/functional/resources/template-change.diff',
             BASE_DIR . '/dev/instances/magentom23/vendor.patch'
@@ -139,6 +145,10 @@ class FunctionalTests extends \PHPUnit\Framework\TestCase
             BASE_DIR . '/dev/instances/magentom23/app/design/frontend/Ampersand/theme/Magento_Bundle/templates/js/components.phtml',
             "This file did not get auto patched properly"
         );
+        copy(
+            BASE_DIR . '/dev/instances/magentom23/vendor/magento/module-bundle/view/frontend/templates/js/components.phtml.orig',
+            BASE_DIR . '/dev/instances/magentom23/vendor/magento/module-bundle/view/frontend/templates/js/components.phtml'
+        );
     }
 
     /**
```

**Comment by hostep** [comment]
Most likely yes, but it's ugly 😄 
But if you're okay with this, it's fine by me 🙂 

Also, I just came to realise that this "problem" should have already existed before this PR.

Let me give it a try here when I find some time later today/this week.

**Comment by hostep** [comment]
I gave it a try but it doesn't seem to solve the problem somehow, first run is fine, second run gives an error:

```
There was 1 failure:

1) FunctionalTests::testAutoApplyPatches
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 '+-------+--------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------------+--------------+\n
 | Level | Type                     | File                                                                     | To Check                                                                         | Auto applied |\n
 +-------+--------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------------+--------------+\n
-| WARN  | Override (phtml/js/html) | vendor/magento/module-bundle/view/frontend/templates/js/components.phtml | app/design/frontend/Ampersand/theme/Magento_Bundle/templates/js/components.phtml | Yes          |\n
+| WARN  | Override (phtml/js/html) | vendor/magento/module-bundle/view/frontend/templates/js/components.phtml | app/design/frontend/Ampersand/theme/Magento_Bundle/templates/js/components.phtml | No           |\n
 +-------+--------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------------+--------------+\n
 WARN count: 1\n
 INFO count: 0\n
 For docs on each check see https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/blob/master/docs/CHECKS_AVAILABLE.md'

/src/dev/phpunit/functional/FunctionalTests.php:158
phpvfscomposer:///src/vendor/phpunit/phpunit/phpunit:97

FAILURES!
Tests: 4, Assertions: 21, Failures: 1.
make: *** [docker-test] Error 1
```

Since these tests takes so long to run on my local and I can't seem to figure it out in less than 20 minutes, let's just proceed without fixing this?


(I'm on a different computer today then yesterday, just FYI: with apple silicon, the tests take about 4 minutes to run, while on a mac with an intel processor, it's about 2 minutes, probably because in the docker files, the platform is hardcoded to `linux/amd64`)

**Pull request merged**
