### PR TITLE
Support reporting issues in all custom themes instead of just one

### LINKED ISSUE #30: Multiple levels of theme inheritance can hide an overwritten template file
Hi!

Detected just now when analysing Magento 2.3.5-p2 upgrade (from 2.3.5-p1).
Regarding the file `vendor/magento/module-wishlist/view/frontend/templates/sidebar.phtml`

We have a particular project where the following theme inheritance is active:
- Magento/blank
  - Vendor/blank (installed in vendor)
    - Vendor/custom (installed in app/design)

The `sidebar.phtml` file is being overwritten in both Vendor themes:
- `vendor/vendor/blank/Magento_Wishlist/templates/sidebar.phtml`
- `app/design/frontend/Vendor/custom/Magento_Wishlist/templates/sidebar.phtml`

When I run the `analyse` command, it only outputs:
- `app/design/frontend/Vendor/custom/Magento_Wishlist/templates/sidebar.phtml`

Is this expected? I think it should output both files?

There is a possibility that one storeview uses one theme and another storeview uses the other theme and then we could have troubles if only one of both was patched.

Thanks again for the awesome tool which I'm using all the time! :)

### PR DESCRIPTION
**Pull request by hostep**
Should fix #30 

We'll also need to verify with @tr33m4n if this doesn't break #21 

### Checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] Tests have been ran / updated

### CODE REVIEW

**Comment by hostep** [comment]
The test for Magento 2.1 fails, because `Magento\Framework\View\Design\Theme\ThemeList` was introduced in Magento 2.2.0

If we need to find a different way of fetching all the themes so Magento 2.1 is still supported, let me know.
But if you are still upgrading to Magento 2.1.x these days, you are doing something wrong in my opinion 🙂

**Comment by tr33m4n** [comment]
@hostep Would you be able to confirm that setting a theme with DI still works and is picked up in your new functionality? If that's the case, all good from me 👍

**Comment by convenient** [comment]
> But if you are still upgrading to Magento 2.1.x these days, you are doing something wrong in my opinion 🙂

I was considering this yesterday in fact :) 

See my comment on https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/pull/29

> Remove 2.1 support? Upgrade from trusty to xenial? might give php 7.4 support

**Comment by convenient** [comment]
@hostep a second thought. 

For any poor sod who _does_ have to upgrade from 2.1 to 2.x in the future it might still be nice if this tool didn't break (even if its not official supported by us).

I wonder if we can do a 
```
if class exists
    do modern approach that detects multiple layers of theme overrides
else 
    do old approach which only finds one level of overrides
```

Speaking as someone who's done some pretty severe magento upgrades in the past it would be nice to at least leave an escape hatch open for our future users.

**Comment by convenient** [comment]
@hostep pushed to your branch

- Remove 2.1 tests. No one is upgrading to a 2.1 series, and this code runs on the version of magento being upgraded to which should be a modern version.
- Set up theme fallback like `Luma <- AmpersandVendor <- Ampersand`, added test case and we can see that a test override is being reported twice
```
| Override (phtml/js/html) | vendor/magento/module-checkout/view/frontend/templates/cart/form.phtml                | app/design/frontend/Ampersand/theme/Magento_Checkout/templates/cart/form.phtml                   |
| Override (phtml/js/html) | vendor/magento/module-checkout/view/frontend/templates/cart/form.phtml                | vendor/ampersand/upgrade-patch-helper-test-module/src/Magento_Checkout/templates/cart/form.phtml |
```

**Pull request merged**
