### PR TITLE
Test third party modules (fix issue #5)

### PR DESCRIPTION
**Pull request by convenient**
Fix issue #5 

Adds ability to use this when upgrading any dependency. In the test process I have added a module `AmpersandVendorTest` and have added a preference and an override for a template to it within `AmpersandTest` and the theme.

This has had the effect that we can see the test module being flagged at https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/pull/50/files?w=1#diff-133b164f15b2fb0ce3b815c485e7c74f359bffb1d7409f7f1969fed6060b94ea (best to avoid whitespace)

This has had the following effect and we can see the test module overrides being flagged.

A bit of a clearer example, I temporarily spoofed in some adyen overrides and got the following.

The process is exactly the same, i did it this way in case a magento module requires a magento module to function. The best guarantee is to diff the whole vendor before and after, rather than trying to be too clever.

```
+--------------------------+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+
| Type                     | Core                                                                                   | To Check                                                                                         |
+--------------------------+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+
| Override (phtml/js/html) | vendor/adyen/module-payment/view/frontend/templates/checkout/success.phtml             | app/design/frontend/Ampersand/theme/Adyen_Payment/templates/checkout/success.phtml               |
| Preference               | vendor/adyen/module-payment/AdminMessage/APIKeyMessage.php                             | Ampersand\Test\Model\AdyenAPIKeyMessage                                                          |
+--------------------------+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+
```

### Checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] Tests have been ran / updated

### CODE REVIEW

**Comment by convenient** [comment]
Hello @PascalBrouwers you said you were interested in this feature [here](https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/issues/34#issuecomment-703672238).

Just if you wanted to try it out or had any feedback :)

**Comment by hostep** [comment]
Hi @convenient, feature sounds really useful!

I just tested this out on a recent project where we upgraded from Magento 2.1.11 to 2.3.6-p1 and also updated a whole bunch of third party modules.

Unfortunately I run into an error when I'm trying it out:
```
bin/patch-helper.php analyse /some/project -vvv
...
Validating vendor/fooman/emailattachments-implementation-m2/src/Model/TermsAndConditionsAttacher.php

In Entry.php line 198:

  [LogicException]
  } does not equal  in vendor/fooman/emailattachments-implementation-m2/src/Model/TermsAndConditionsAttacher.php on line 74


Exception trace:
 () at src/Ampersand/PatchHelper/Patchfile/Entry.php:198
 Ampersand\PatchHelper\Patchfile\Entry->getAffectedFunction() at src/Ampersand/PatchHelper/Patchfile/Entry.php:159
 Ampersand\PatchHelper\Patchfile\Entry->getAffectedInterceptablePhpFunctions() at src/Ampersand/PatchHelper/Helper/PatchOverrideValidator.php:256
 Ampersand\PatchHelper\Helper\PatchOverrideValidator->validatePhpFileForPlugins() at src/Ampersand/PatchHelper/Helper/PatchOverrideValidator.php:120
 Ampersand\PatchHelper\Helper\PatchOverrideValidator->validate() at src/Ampersand/PatchHelper/Command/AnalyseCommand.php:81
 Ampersand\PatchHelper\Command\AnalyseCommand->execute() at vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at vendor/symfony/console/Application.php:953
 Symfony\Component\Console\Application->doRunCommand() at vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at bin/patch-helper.php:10

analyse [-a|--auto-theme-update [AUTO-THEME-UPDATE]] [--sort-by-type] [--vendor-namespaces [VENDOR-NAMESPACES]] [--php-strict-errors] [--] <project>
```

That module from fooman is opensource, so hopefully you'll be able to test this as well: https://github.com/fooman/emailattachments-implementation-m2
We upgraded it from version 104.0.4 to 107.1.1

The diff of that particular file in the `vendor.patch` file looks like this:
```diff
diff -ur vendor_orig/fooman/emailattachments-implementation-m2/src/Model/TermsAndConditionsAttacher.php vendor/fooman/emailattachments-implementation-m2/src/Model/TermsAndConditionsAttacher.php
--- vendor_orig/fooman/emailattachments-implementation-m2/src/Model/TermsAndConditionsAttacher.php      2021-03-11 11:34:21.000000000 +0100
+++ vendor/fooman/emailattachments-implementation-m2/src/Model/TermsAndConditionsAttacher.php   2020-12-10 21:55:14.000000000 +0100
@@ -1,18 +1,17 @@
 <?php
+declare(strict_types=1);
+
+namespace Fooman\EmailAttachments\Model;
+
+use Fooman\EmailAttachments\Model\Api\AttachmentContainerInterface as ContainerInterface;
+use Magento\CheckoutAgreements\Api\Data\AgreementInterface;
+
 /**
- * @author     Kristof Ringleff
- * @package    Fooman_EmailAttachments
  * @copyright  Copyright (c) 2015 Fooman Limited (http://www.fooman.co.nz)
  *
  * For the full copyright and license information, please view the LICENSE
  * file that was distributed with this source code.
  */
-
-namespace Fooman\EmailAttachments\Model;
-
-use \Fooman\EmailAttachments\Model\Api\AttachmentContainerInterface as ContainerInterface;
-use \Magento\CheckoutAgreements\Api\Data\AgreementInterface;
-
 class TermsAndConditionsAttacher
 {
     private $termsCollection;
@@ -30,7 +29,7 @@
     public function attachForStore($storeId, ContainerInterface $attachmentContainer)
     {
         /**
-         * @var $agreements \Magento\CheckoutAgreements\Model\ResourceModel\Agreement\Collection
+         * @var \Magento\CheckoutAgreements\Model\ResourceModel\Agreement\Collection $agreements
          */
         $agreements = $this->termsCollection->create();
         $agreements->addStoreFilter($storeId)->addFieldToFilter('is_active', 1);
@@ -71,4 +70,4 @@
             $agreement->getContent()
         );
     }
-}
\ No newline at end of file
+}
```

Hope this is useful and that you can reproduce the problem and figure out a solution 🤞

**Comment by convenient** [comment]
@hostep Thanks for the detailed info! It's definitely about the newline being added to the end of the file, I should definitely be able to reproduce this. 

This is the first time this exception has actually thrown to my knowledge, i wonder if its worthwhile relaxing it so it doesnt break the entire tool in these scenarios but instead fails to work out potential plugins for the file? 🤔

**Comment by hostep** [comment]
Well, it makes sense this is the first time, because Magento's coding standards force you to have a newline at the bottom of all php files as far as I'm aware. So this will only happen with 3rd party plugins.
However, I don't think this should stop working out plugins for such files, the patchfile code should probably try to workaround such occurrences if that is possible somehow.

**Comment by convenient** [comment]
@hostep Of course I intend to fix this so the patchfile code can understand this line ending glitch (and I'll also try to find a file with windows line endings to test against). However as this change to scan third party modules will broaden the scope of files scanned to a wide variety or different styles and quality ranging from good to bad, I am wondering if I can reliably cater for all the possible variations of magento modules out there.

Perhaps I could have it be like 

```
bin/patch-helper.php analyse /some/project
LogicException: Could not understand file vendor/fooman/emailattachments-implementation-m2/src/Model/TermsAndConditionsAttacher.php

Please re-run this command with --suppress-plugin-detection-errors.
Please raise an issue at https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/issues with the following details X/Y/Z
```

I cant imagine what issues we will see after the line endings are handled, if any. However I'm cautious that this could very well break this tool for a lot of users if there are third party modules out there that do things in really really weird ways. Like, i dont know, is ioncube still a thing? Or obfuscated files 🤔 

I just want to avoid merging this in and it going 💥  for many users. Any thoughts?

**Comment by convenient** [comment]
Or maybe I could
- have the tool run to completion
- Catch and aggregate all these logic exceptions into a separate stream of output in the console, telling them that plugin detection failed for files X/Y/Z
- Dump the unparseable patchfile entries into `vendor_files_error.patch`
- Notify the user to raise an issue with the X/Y/Z files and the `vendor_files_error.patch` file 

I think thats the best of both worlds. Allows the tool to "just work" for most cases, and gives clear indication that something is wrong and needs fixed.

**Comment by hostep** [comment]
Ah sorry, I misunderstood your comment, now it makes sense 🙂 
Yeah, outputting warnings about unparsable files seems like a good idea and keep the tool running if it encounters them by skipping them.

**Comment by convenient** [comment]
@hostep  Next week I will
1. Add a commit to keep this tool running in the event of these errors and output some debug information.
2. Fix the handling of the newline at end of files. This should be trivial to capture in a unit test.

**Comment by convenient** [comment]
Hehe, I am happy to see even the git core sometimes misses the handling of `\ No newline at end of file`

https://github.com/git/git/commit/2485eab55cc0dcab34311ecd0ac52038aa9d9db4

**Comment by convenient** [comment]
@hostep  Would you be able to review please? After looking at this bug I am pretty happy that its just the newline issue but have added the mentioned outputting of errors anyway just in case.
 
# Capturing the issue

In 70a610c8fddbbae45d35fb5ce008fb84f7c40413 I added a test to capture the issue

https://travis-ci.org/github/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/jobs/762945924
```
$ vendor/bin/phpunit -c dev/phpunit/unit/phpunit.xml --verbose;
PHPUnit 7.5.2 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.4.15
Configuration: /home/travis/build/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/dev/phpunit/unit/phpunit.xml
E.........                                                        10 / 10 (100%)
Time: 32 ms, Memory: 4.00MB
There was 1 error:
1) EntryTest::testNewlineAtEndOfFile
Ampersand\PatchHelper\Exception\PluginDetectionException: vendor/TermsAndConditionsAttacher.php - on line 5 - } does not equal 
/home/travis/build/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/src/Ampersand/PatchHelper/Patchfile/Entry.php:201
/home/travis/build/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/src/Ampersand/PatchHelper/Patchfile/Entry.php:161
/home/travis/build/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/dev/phpunit/unit/Ampersand/PatchHelper/Patchfile/EntryTest.php:17
ERRORS!
Tests: 10, Assertions: 18, Errors: 1.
```

I also modified the script so that it output this issue like the following
Screenshot 2021-03-15 at 10 16 35

This will make this tool more robust in these scenarios.

# Fixing the bug

See 3b3fd819e9795fbc866ffb6a5781f6b5aab17fc0 for the fix

The issue here is with diffs like this
```
diff -ur vendor_orig/TermsAndConditionsAttacher.php vendor/TermsAndConditionsAttacher.php
--- vendor_orig/TermsAndConditionsAttacher.php	2021-03-12 13:06:24.000000000 +0000
+++ vendor/TermsAndConditionsAttacher.php	2021-03-12 13:06:10.000000000 +0000
@@ -1,4 +1,4 @@
 <?php
 class TermsAndConditionsAttacher
 {
-}
\ No newline at end of file
+}
```

The problem is that the line `\ No newline at end of file` is being treated as a context line, despite it not actually being a context line. 

I was curious how the git core handled it and found this commit https://github.com/git/git/commit/82a62015a7b55a56f779b9ddfb98a3b0552d2bb4#diff-f7c7f3bcdd495dd2b0caa9b52b52ff4404e34a0039a187237e5a817199c0b2beR6047 which has this comment

> If that newline is missing, however, diff reports that fact in a separate line containing "\ No newline at
end of file\n", and this marker is hashed like a context line. 
> ....
> and skip diff lines that start with a backslash and a space and are longer than twelve characters.

So our solution here shall be the same as the git core. I am not sure why 12 chars, but thats what they use in two places that I can find linked from that commit.

**Comment by hostep** [comment]
Nice, I can confirm that the tool is no longer crashing and it achieves what is desired.

One thing I'm noticing is: a third party module which is bundled in a couple of submodules can report one of its own bundled modules as causing a potential issue, a Plugin in my case (but I'm fine with that, as it will be very hard to figure out a solution for this)

However, I'm seeing some more differences between `master` and `test-third-party-modules` branches which might not be expected.
1. It no longer detect "some" overwritten `phtml` file in a custom theme (2 files out of 54 files), not exactly sure what's going on there ...
2. Certain Plugins are no longer being reported, even though the original method they plugin before/around/after still changed some code (5 out of 59 plugins)
3. I see a similar problem with 1 preference out of 17 preferences, that is no longer being outputted

So it looks like we have a bunch of regressions somewhere in these changes.

Unfortunately I won't find time anymore today to further dig in and provide you with more details. I'll try to give you more info later this week if possible 🙂

**Comment by convenient** [comment]
@hostep  Thanks for the updates

>It no longer detect "some" overwritten phtml files in a custom theme (2 files out of 54 files), not exactly sure what's going on there ...

It may be possible that they're not being flagged as valid scannable modules 🤔  Maybe I need to add list of themes like i did librarys here 4b037758425f5c27e8133af6c4063b4c4d78b519 however this didnt affect any of my test cases.

>Certain Plugins are no longer being reported, even though the original method they plugin before/around/after still changed some code (5 out of 59 plugins)
I see a similar problem with 1 preference out of 17 preferences, that is no longer being outputted

Same as above perhaps, I cannot see anything that would prevent plugins being reported other than them being excluded from this list.

If you can run with `-vvv` and see if they're being skipped or scanned even that could be useful?

Thanks

**Comment by hostep** [comment]
@convenient: ok I think I've found the problem (not in code, but by looking closer at the output)

So, If I execute with the `-vvv` flag, I did notice 2 errors about those 2 missing frontend files, for example:
```
Could not understand vendor/magento/module-catalog-widget/view/frontend/templates/product/widget/content/grid.phtml: Could not resolve app/code/Magento/Catalog-widget/view/frontend/templates/product/widget/content/grid.phtml (attempted to resolve to )
```

What I'm noticing here is that it goes from `module-catalog-widget` to `Catalog-widget`, which is incorrect, it should become `CatalogWidget`. So there is something going wrong when you try to transform the name of those modules when they have more then one `-` in their directory name.

Once I noticed this, I took another look at all those other missing files, and yes, all those are from modules which have at least 2 `-` in their directory names:
- `vendor/magento/module-catalog-widget/`
- `vendor/magento/module-configurable-product/`
- `vendor/magento/module-catalog-search/`
- `vendor/magento/module-catalog-widget/`
- ...

Not sure where this is done in code, but I hope you'll now be able to figure this out with this extra info 🙂

**Comment by convenient** [comment]
Thank you @hostep I think I've got an idea of whats happening here :)

**Comment by convenient** [comment]
@hostep has confirmed to me on slack that 61405cd has worked. I will now merge and tag.

**Comment by hostep** [comment]
Thank you very much for your work on this @convenient !

@peterjaap will now be able to use even more automatism in his workflow as [he explained in "the registry" podcast](https://podcast.theregistry.io/5) a couple of weeks ago 😉

**Comment by peterjaap** [comment]
Awwww yes, sweet stuff coming up!

**Comment by convenient** [comment]
😀 thank you both for testing @hostep  and @peterjaap 

Yes peters work has inspired me to up my CI game and get this plugged in. I'm thinking of ways of getting this to run automatically when changes are detected in `composer.lock`

**Pull request merged**
